### ISSUE TITLE
Data Structures

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/ex_to_js#19]
Need to figure out how to represent the data structures. The main concern is whatever is chosen, they are able to be destructured. Whether that means using some of the destructing features in ES6 or implementing some destructing feature ourselves  We have:

* Tuple
* Bitstring
* List
* Map
* Struct
* Keyword 
* Dict
* Set

I've gone back and forth on tuples. What I'm currently working on has tuples going from this in Elixir

```elixir
{ value1, value2}
```
to this in JavaScript
```javascript
{'0': value1, '1': value2 }
```

The reason being so that they look different than lists (currently both lists and tuples are turned into arrays) and to allow destructing using the new feature in ES6. Looking on any feedback on this change.

I still haven't figure out how bitstrings would carry over.

Maps and Structs are difficult too. Currently, maps are turned into objects and Structs turned into classes. The idea being that when you defined a struct, you could have default values and that is taken into account. I would prefer to have maps and structs both be turned into the same thing (maybe objects). If that were to happen would need a way to take into account default values set on structs. If they are both turned into objects then that makes destructuring for both an easy task.

**Comment by bryanjos** [comment]
Playing around a bit, I think I've come up with a solution to the map/struct issue. For maps, they will remain objects. For structs, if you have a struct like so 

```elixir
defmodule User do
  defstruct name: "john", age: 27
end

user = %User{name: "john"}
```

this would be turned into the following in JavaScript

```javascript
const __MODULE__ = Symbol('User')

export function defstruct(name: "john", age: 27){
  return {__struct__: __MODULE__, name: name, age: 27}
}

user = defstruct(name: "john");
```

 __MODULE__ must be added to every module anyway.

This allows for destructuring and looks more how structs are represented in Elixir.

**Comment by togakangaroo** [comment]
Personally I think `{'0': value1, '1': value2 }` is kind of misleading in that it looks like an array, is used like an array, but isn't an array.

How frustrating will it be the first time someone interfaces with this structure in js and tries to call `.length`?

I'd much prefer `{'_0': value1, '_1': value2 }` or `{'t0': value1, 't1': value2 }`

**Comment by bryanjos** [comment]
I can agree with either of those. I'll pick one at random and go with the underscore version. The key doesn't matter at all, but it's as close to the tuple structure as I can see and it helps with destructuring. And you're right and that I don't want to confuse anyone.

**Comment by bryanjos** [comment]
Saw an older issue on the LuvvieScript repo about possibly using Typed Arrays for an implementation of bitstrings. That could be at least a good thing to look into

**Comment by bryanjos** [comment]
I'm going to close this. Dict and Set are the only ones remaining and those will be implemented with the rest of the standard lib.
