### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/ex_to_js#36]
Any suggestions?

I think everyone so far assumes "ElixirScript", but I'm not 100% sold on that. It may end up being the name though.

 I like "ExScript" but a quick Google search showed there is already a project with that name. I also like "ElixirJS".

**Comment by scrogson** [comment]
ElixirScript seems the best option. I'm a :-1: for ExScript.

**Comment by elia** [comment]
I like ElixirJS too

**Comment by bryanjos** [comment]
ExScript has fallen out of favor with me too. 

ElixirScript is in the lead followed by ElixirJS. It's already ElixirScript in the code. It probably is the best option, but wanted to get some feedback to see what people were thinking.

**Comment by bryanjos** [comment]
After thinking about it some more, I think ElixirScript is the best choice. People already call it that and it's that name in the code already. I'm going to change the repo name today to match.
